/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:ae239d91-037a-4375-b5ab-4d9a1972b18d",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_lgW307qQR",
    "aws_user_pools_web_client_id": "3um8veqodnsp0krvd0f7argaer",
    "oauth": {}
};


export default awsmobile;
